# This is a basic workflow to help you get started with Actions

name: ServiceNow CI/CD Pipeline with QualityClouds LiveCheck

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    # Purpose of this job is to Apply Remote Changes for the branch triggering 
    # the pipeline build to the Dev instance, then publish the application to 
    # app repo using the template versioning format. 
    name: Publish from Dev
    runs-on: ubuntu-latest
    # Below line can be used to set conditionals for modifying your pipeline as needed.
    # if: ${{ github.event_name == 'pull_request'}}

    steps:
      - uses: actions/checkout@v2
      - name: QualityClouds CI/CD BuildCheck for Servicenow
        uses: qualityclouds/action-snow-full-scan@0.0.5
        with:
          token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjQ5MzMwN2M1YzA3MTRjNjNjNGZmMDkxMjU3NTRmODk5OWZjZjE4YzNlOTFkYmE1NzcwZDM2Y2UxNWQ0Mzk1ZmE4ZWQyN2FlNmJiYzE2ZDgwIn0.eyJhdWQiOiIyIiwianRpIjoiNDkzMzA3YzVjMDcxNGM2M2M0ZmYwOTEyNTc1NGY4OTk5ZmNmMThjM2U5MWRiYTU3NzBkMzZjZTE1ZDQzOTVmYThlZDI3YWU2YmJjMTZkODAiLCJpYXQiOjE2Mzc1ODc3NDIsIm5iZiI6MTYzNzU4Nzc0MiwiZXhwIjoxNjY5MTIzNzQyLCJzdWIiOiI3OTEiLCJzY29wZXMiOlsibGl2ZS1jaGVjayJdfQ.e-T9uFXAeWddUr5tmxKnlsUu8vfv7lXchbQWo14zfh6KT9E2etin4rQNYBUbswJHa_4gMfbqwXMqLmCyBCZdGwb5nMbB2YBXS0Lk0RM0hbKTvzfRlvVZtLdareQzv2LgS3TvOWZb9QpqglINA2ONdw6qAluFV5GaSf4zXEd3Awo5dFKhLuJ2h4Fs4i6RWu0pYj05lb4kciGa2dov84B_Rrz0ksj1OSAejohAwssBtNY5rKgbOaf1XA1IjJvbMtxX7GsDZvkSS8Ts9zS9OR5zOmxrYVBSy-PVmNssmaCsJIYOF0Pai15gN23ZFECABp2z6LP3sgaq6bcS4HLBeWFmZvar2qtylvVnc3U0MsGP3hWBc17iRoKtU6RN5Hyjk3R_GhAA5KabLJBz7kVHj04nL-fPy0H70wVy_EBfVIYS3Vrkx58RRw8GFJKPILlutFFMa7RtgVX_WX4mrc1UPy4ml8fjsl4Ol8mq-3qadITVBYUQpmTs69iRZZpwOlsH-BXXuAw_EzSaleaHyp-qiOd1lk9IRuq0FjRYqygvyUx3Fb8xCl_PuYUDN6ZcijMewCuRp5d12PAWwFe8CtPn7jQJZ1yMAj_yJjCtRvGEOlsfgMMcYbNPzEd295McTdp5zzePHqmMB4saN9Hs6R-AajBQYugl6oC2WoQ9i6EOM7yCx2Y'
          instance_url: 'https://dev78278.service-now.com'
          api_url: "https://api.qualityclouds.com"
